
services:
  db:
    image: postgres:16-alpine
    container_name: orbis-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orbis
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - orbis-network

  backend:
    build: ./backend
    container_name: orbis-backend
    env_file:
      - ./backend/.env
    depends_on:
      - db
    expose:
      - "4000"
    networks:
      - orbis-network

  frontend:
    build: ./frontend
    container_name: orbis-frontend
    env_file:
      - ./frontend/.env
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - orbis-network

volumes:
  pgdata:

networks:
  orbis-network:
    driver: bridge

