version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: orbis-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orbis
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: orbis-backend
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    build: ./frontend
    container_name: orbis-frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres-data:

