services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - orbis-network

  backend:
    build: ./backend
    expose:
      - "4000"
    networks:
      - orbis-network

  frontend:
    build: ./frontend
    expose:
      - "80"
    networks:
      - orbis-network

  nginx:
    image: nginx:latest
    container_name: orbis-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - backend
      - frontend
    networks:
      - orbis-network

volumes:
  pgdata:

networks:
  orbis-network:
    driver: bridge

